"""
Django settings for irock project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

import os


# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# BASE_URL ="http://localhost:8000"

# BASE_DIR = Path(__file__).resolve().parent.parent
#BASE_URL ="https://irockinfo.mo.vc"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qzl@9ieb1tdan$jzbj&dh)_kd(e0w4qthhc(4^1xyqmbwty=t6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'custom_auth',
    'projects',
    'notifications',
    'notification',
    'widget_tweaks',
    'corsheaders',
    'invoice',
    'chat',
    'channels',
    'credit_note',
    'import_export',
    'InvoiceGuard',
    'finance',
    'cost_code',
    'wcc',
    'projectflow',
    'invoiceview',
    'dashboard'

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'irock.middleware.tenant_middleware',
    # 'irock.middleware.user_middleware',
    'irock.middleware.TimezoneMiddleware',
    # 'irock.session_check_middleware.SessionCheckMiddleware',
    

]

# X_FRAME_OPTIONS = 'ALLOW-FROM http://127.0.0.1:8000/chat/0/'
X_FRAME_OPTIONS = 'ALLOW-FROM https://irockinfo.mo.vc/chat/0/'





ROOT_URLCONF = 'irock.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
         
            ],
        },
    },
]

WSGI_APPLICATION = 'irock.wsgi.application'
DJANGO_NOTIFICATIONS_CONFIG = { 'USE_JSONFIELD': True}



# ASGI_APPLICATION = "irockmsg.asgi.application"
# Channels

ASGI_APPLICATION = 'irock.asgi.application'
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayrer',
#     },
# }

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
        #    "hosts": [('143.1.1.122', 6379)],
            # "hosts": [('redis.mo.vc')],
            "hosts": [('redis.mo.vc',8081)],
        },
    },
}






# CSRF_TRUSTED_ORIGINS = ['https://irockinfo.mo.vc/']

#
# CORS_ALLOWED_ORIGINS = [
#     'http://127.0.0.1:8000',
#     'http://localhost:8000',
#     # 'https://irockinfo.mo.vc/',
# ]
# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {  
    'default': {  
        'ENGINE': 'django.db.backends.mysql',  
        'NAME': 'irockdev',
        'USER':'irock-dev',  
        'PASSWORD':'Solution@456',  
        'HOST':'127.0.0.1',  
        'PORT':'3306'  
    }  
} 


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
#STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, "static"), 
#]
LOGIN_REDIRECT_URL = '/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTH_USER_MODEL = 'custom_auth.User'

# Default primary key field type

USE_THOUSAND_SEPARATOR = False
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = "ibytesvc@gmail.com"
# EMAIL_HOST_PASSWORD = "lufrlhyjedbistfa"
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "client100785@gmail.com"
EMAIL_HOST_PASSWORD = "rcusxpiepfgtngkd"
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# DEFAULT_FROM_EMAIL='Ajaykumar<noreplay@gmail.com>
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# MAIL_MAILER='smtp'
# MAIL_HOST='smtp.gmail.com'
# MAIL_PORT=465
# MAIL_USERNAME='ibytesvc@gmail.com'
# MAIL_PASSWORD='zfhwwepxubukfcmb'
# MAIL_ENCRYPTION='ssl'
# MAIL_FROM_ADDRESS='ibytesvc@gmail.com'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'




DATA_UPLOAD_MAX_NUMBER_FIELDS = 102400


